ListaCompras/urls.py
from django.contrib import admin
from django.urls import path, include

## Cargan las imagenes en desarrollo
from django.conf.urls.static import static
from django.conf import settings

urlpatterns =  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls),  
    path('', include('gestion_usuario.urls')),
] 

gestion_usuario/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'gestion_usuario'

urlpatterns = [
    url('registrar/', views.registrar, name='registrar'),
    url('login/', views.usuario_login, name='login'),
    url('logout/', views.usuario_logout, name='logout'),
    path('add', views.add, name= 'add'),
    path('listar',views.listar, name='listar'),
    path('dolar', views.dolar, name= 'dolar'),
    
    
    
    
    url('', views.index, name='index')
]

gestion_usuario/models.py
from django.db import models
from django.contrib.auth.models import User

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Para aplicar imagefiel necesitamos instalar Pillows -> pip install Pillow
    foto_perfil = models.ImageField(upload_to='foto_perfil', blank=True)
    def __str__(self):
        return self.user.username




class Producto(models.Model):
    nombreproducto = models.CharField(max_length=100)
    costopresupuestado = models.IntegerField()
    precioproducto = models.IntegerField()
    tienda = models.CharField(max_length=100)
    nota = models.CharField(max_length=200)

    
    

gestion_usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import PerfilUsuario
from .models import Producto
from django.forms import ModelForm




class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = ['nombreproducto','precioproducto','costopresupuestado','tienda','nota']
        labels = {
            'nombreproducto': 'Nombre del Producto',
            'precioproducto': 'Precio',
            'costopresupuestado': 'Costo presupuestado',
            'tienda':'Local procedencia',
            'nota': 'Comentario',
        }
    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        self.fields['nombreproducto'].widget.attrs.update({'class': 'form-control'})
        self.fields['precioproducto'].widget.attrs.update({'class': 'form-control'})
        self.fields['costopresupuestado'].widget.attrs.update({'class': 'form-control'})   
        self.fields['tienda'].widget.attrs.update({'class': 'form-control'})
        self.fields['nota'].widget.attrs.update({'class': 'form-control'}) 
                
                
       

    


class   PerfilUsuarioForm(forms.ModelForm):
    class Meta():
        model = PerfilUsuario
        fields = ('foto_perfil',)
        # Labels nos cambia el texto del label que corresponde al input
        labels = {
            'foto_perfil': 'Foto de perfil'
        }

class RegistrarForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')
    class Meta:
        model = User
        fields = ('username', 
                'email', 
                'password')
        labels = {
            'username': 'Nombre de usuario',
            'email': 'Correo',
            'password': 'Contraseña'
        }
        help_texts = {
            'username': '',
        }
        error_messages = {
            'username': {
                'max_length': 'Maximo 150 caracteres',
                'required': 'Requerido'
            },
            'password': {
                'required': 'Requerido'
            }
        }

    # Define el class="form-control" dentro de los labels del formulario
    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

gestion_usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import RegistrarForm, PerfilUsuarioForm,ProductoForm, Producto

# Cierre de sesion

def dolar(request):
    return render(request, 'presupuestador/api_dolar.html', {})

def usuario_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('gestion_usuario:index'))

def index(request):
    return render(request, 'gestion_usuario/index.html', {})    
       

def usuario_login(request): 
    # Valida si existe un usuario autenticado
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse, ('gestion_usuario:index'))
    else:
        # Recibe formulario mediante metodo POST
        if request.method == 'POST':
            # Recibimos la informacion del formulario
            username = request.POST.get('username')
            password = request.POST.get('password')
            # Autenticamos el usuario
            user = authenticate(username=username, password=password)
            # Verifica que exista el usuario
            if user:
                # Verifica si el usuario esta activo
                if user.is_active:
                    # Genera un login para autenticar al usuario
                    login(request, user)
                    return HttpResponseRedirect(reverse('gestion_usuario:index'))
                else:
                    return HttpResponse("Tu cuenta esta inactiva.")
            else:
                # Si no existe usuario
                print("username: {} - password: {}".format(username, password))
                return HttpResponse("Datos inválidos")
        else:  # Si llega desde una url en metodo GET (desde el navegador)
            return render(request, 'gestion_usuario/login.html', {})

def registrar(request):
    registrado = False
    # Recibe formulario mediante metodo POST
    if request.method == 'POST':
        # Crea formulario de usuario con informacion del request
        user_form = RegistrarForm(data=request.POST)
        # Crea formulario de perfil con informacion del request
        profile_form = PerfilUsuarioForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            # Guardamos en base de datos
            user = user_form.save()
            # Encripta password con el modelo de django
            user.set_password(user.password)
            # Guarda usuario tras encriptacion
            user.save()
            # Instancia un objeto perfil
            profile = profile_form.save(commit=False)
            # Asigna un usario al perfil
            profile.user = user
            # Valida si en el Array FILES existe el archivo del input foto_perfil
            if 'foto_perfil' in request.FILES:
                # Agrega la imagen al perfil
                profile.foto_perfil = request.FILES['foto_perfil']
            # Guarda en base de datos
            profile.save()
            registrado = True
        else:  # Si alguno de los formularios es invalido
            print(user_form.errors, profile_form.errors)
            return HttpResponse("Datos inválidos")
    else:  # Si no es POST generamos los formularios
        user_form = RegistrarForm()
        profile_form = PerfilUsuarioForm()

    return render(request, 'gestion_usuario/registrar.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registrado': registrado})

 
def listar(request):
    if request.user.is_authenticated:
        # creamos una colección la cual carga TODOS los registos
        productos = Producto.objects.all()
        # renderizamos la colección en el template
        return render(request,
            "presupuestador/listar.html", {'productos': productos})
    else:
        return render(request, 'principal.html', {})

def add(request):
    # Creamos un formulario vacío
    form = ProductoForm()

    # Comprobamos si se ha enviado el formulario
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = ProductoForm(request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Guardamos el formulario pero sin confirmarlo,
            # así conseguiremos una instancia para manejarla
            instancia = form.save(commit=False)
            # Podemos guardarla cuando queramos
            instancia.save()
            # Después de guardar redireccionamos a la lista
            return redirect('presupuestador/listar.html')
            

    # Si llegamos al final renderizamos el formulario
    return render(request, "presupuestador/add.html", {'form': form})

gestion_usuario/templates/gestion_usuario/index.html
{% extends 'base.html' %}
<!-- ////////////////////////////////////////////////// -->
{% block content %}


<!-- Page Content -->
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">
      <h1 class="font-weight-light">Bienvenido a Manage Money</h1>
      
      

      <div class="jumbotron">
        <h1 class="display-4">¿Que puedes hacer?</h1>
        <p class="lead">
          En este sitio puedes elaborar listas de compra con la finalidad
          de ordenar tus presupuestos de gastos y mejorar sus finanzas 
        </p>
        <hr class="my-4" />
        <p>
        
        </p>
        {% if not request.user.is_authenticated %}
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'gestion_usuario:registrar' %}" role="button"
            >¡Comienza ya! </a>
        </p>
        {% else %}
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'gestion_usuario:add' %}" role="button"
            >¡Agrega un Producto!</a>
        </p>
        {% endif %}
        

      </div>
      
      
    </div>
  </div>
</div>
{% endblock %}

gestion_usuario/templates/gestion_usuario/login.html
{% extends 'base.html' %}

{% load static %}
<!-- ////////////////////////////////////////////////// -->
{% block head %}
    <link href="{% static 'gestion_usuario/estilo.css' %}" rel="stylesheet"
    
{% endblock head %}
<!-- ////////////////////////////////////////////////// -->
{% block content %}

    <div class="login">
    <br>
        <h1>Iniciar sesión</h1>
        <form method="post" class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username" placeholder="Usuario">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" placeholder="Contraseña">
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
    </div>
{% endblock content %}
<!-- ////////////////////////////////////////////////// -->

gestion_usuario/templates/gestion_usuario/registrar.html
{% extends 'base.html' %}
<!-- ////////////////////////////////////////////////// -->
{% block head %}
<title> Registrar usuario </title>
{% endblock head %}
{% block content %}
    <div class="jumbotron">
        {% if registrado %}
            <h1>Gracias por registrarte</h1>
        {% else %}
            <h1>Registro</h1>
            <h3>Completa los siguiente datos</h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p}}
                <button type="submit" class="btn btn-success">Registrar</button>
            </form>
        {% endif %}
    </div>
{% endblock content %}
<!-- ////////////////////////////////////////////////// -->

gestion_usuario/templates/presupuestador/add.html
{% extends 'base.html' %}

{% block content %}
    <h1> Agregar Producto</h1>

    <form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Crear</button>
</form>




{% endblock %}

gestion_usuario/templates/presupuestador/api_dolar.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--- JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>API</title>
</head>

<body>
    <div class="container">
        <div class="section">
            <button type="button" class="btn btn-primary"
             id="dolar">Mostrar</button>
             <div>Fuente:
                <p id="autor"></p>
            </div>
        </div>
        
        <div>
            
            <div>
                <p id="nombre">Tipo Moneda</p>
            </div>
        </div>
        <div><p id="desplegar-tabla"></p></div>
        
    </div>
    <script src="/static/js/script_indicadores.js"></script>
</body>
</html>



{% endblock %}

gestion_usuario/templates/presupuestador/listar.html
{% extends 'base.html' %}
<!-- ////////////////////////////////////////////////// -->
{% block content %}
    <br>
    
    <h1 class="display-3">Lista de productos</h1>

    
    <br>    
    {{ mensaje }}
    <br>
    <table class="table">
        <thead class="thead-light">
            <tr>
            <th>Nombre</th>
            <th>Valor Real</th>
            <th>Valor Presupuestado</th>
            <th>Local Procedencia</th>
            <th>Comentario</th>
            </tr>
        </thead>
        <tbody>
        {% for s in productos %}
            <tr>
            <td>{{ s.nombreproducto}}</td>
            <td>{{ s.precioproducto}}</td>
            <td>{{ s.costopresupuestado}}</td>
            <td>{{ s.tienda}}</td>
            <td>{{ s.nota}}</td>
            
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}
<!-- ////////////////////////////////////////////////// -->

templates/base.html
{% load static%}
<!DOCTYPE html>
<html>

 <head>
    <script src="{% static 'js/jquery-3.4.1.js' %}"> </script>
    <script src="{% static 'js/bootstrap.js' %}"> </script>
    <link href="{% static  'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static  'css/base_style.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock %}

 </head>

 <body>
     <div class="container">
     <nav id="cont-nav-color" class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">ManageMoney</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navegadorContenido"
            aria-controls="navegadorContenido" aria-expanded="false" aria-label="Navegacion">
            <i class="icon ion-md-menu text-dark"></i>
        </button>
        
        <div class="collapse navbar-collapse" id="navegadorContenido">
            <ul class="navbar-nav ml-auto">
              {% if not request.user.is_authenticated %}
                <li class="nav-item mx-2">
                  <a class="nav-link" href="{% url 'gestion_usuario:index' %}">Inicio</a>
                </li>
              
                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:login' %}">Iniciar sesión</a>
                </li>
                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:registrar' %}">Registrar</a>
                </li>
              {% else %}
                <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'gestion_usuario:listar' %}">Lista</a>
                </li>

                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:add' %}">Agregar Producto</a>
                </li>
                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:dolar' %}">Precio Dolar</a>
                </li>
                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:index' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item mx-1">
                  <a class="nav-link" href="{% url 'gestion_usuario:logout' %}">Cerrar sesión</a>
                </li>
                
                
              {% endif %}
            </ul>
        </div> 
     </nav>


        {% block content %}
        {% endblock %}
     </div>

 
 </body>